#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Phase#3 benchmark configuration, uses Fabric Gateway SDK, where the "targetOrganizations" attribute is available

---
test:
    workers:
        number: 2
    rounds:
    - label: init-no-targets-set
      txNumber: 100
      rateControl: { type: 'fixed-load',   opts: { "transactionLoad": 5, "startTps": 100 }}
      workload:
        module: ./../init.js
        arguments:
          marblePrefix: marble_phase3
          setTargetChannel: false
          setTargetOrganizations: false
    - label: init-target-channel-set
      txNumber: 25
      rateControl: { type: 'linear-rate', opts: { startingTps: 10, finishingTps: 20 } }
      workload:
        module: ./../init.js
        arguments:
          marblePrefix: marble_phase3
          setTargetChannel: true
          setTargetOrganizations: false
    - label: init-target-org-set
      txNumber: 25
      rateControl: { type: 'fixed-rate', opts: { tps: 5 } }
      workload:
        module: ./../init.js
        arguments:
          marblePrefix: marble_phase3
          setTargetChannel: false
          setTargetOrganizations: true
    - label: query-no-targets-set
      txNumber: 200
      rateControl: { type: 'fixed-feedback-rate', opts: { tps: 20, maximum_transaction_load: 5 } }
      workload:
        module: ./../query.js
        arguments:
          setTargetChannel: false
          setTargetOrganizations: false
    - label: query-target-channel-set
      txNumber: 25
      rateControl: { type: 'linear-rate', opts: { startingTps: 5, finishingTps: 10 } }
      workload:
        module: ./../query.js
        arguments:
          setTargetChannel: true
          setTargetOrganizations: true
monitors:
    transaction:
    - module: prometheus-push
      options:
        pushInterval: 5000
        pushUrl: "http://localhost:9091"
    resource:
    - module: prometheus
      options:
        url: "http://localhost:9090"
        metrics:
            include: [peer*, dev*]
            queries:
            - name: Endorse Time (s)
              query: rate(endorser_propsal_duration_sum{chaincode="marbles:v0"}[1m])/rate(endorser_propsal_duration_count{chaincode="marbles:v0"}[1m])
              step: 1
              label: instance
              statistic: avg
            - name: Max Memory (MB)
              query: sum(container_memory_rss{name=~".+"}) by (name)
              step: 10
              label: name
              statistic: max
              multiplier: 0.000001
        charting:
            polar:
                metrics: [Max Memory (MB)]
            bar:
                metrics: [all]
    - module: process
      options:
        interval: 3
        processes: [{ command: 'node', arguments: 'caliper.js', multiOutput: 'avg' }]
    - module: docker
      options:
        interval: 4
        containers: ['peer0.org1.example.com', 'peer0.org2.example.com', 'orderer0.example.com', 'orderer1.example.com']

