name: CI (Publish)

on:
  push:
    branches: [ "main" ]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  coverage:
    uses: ./.github/workflows/coverage.yml
    needs: unit-tests
  publish-caliper:
    uses: ./.github/workflows/publish.yml
    needs: unit-tests
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
