name: Publish

on:
  workflow_call:
    secrets:
      DOCKER_TOKEN:
        required: true
      DOCKER_USER:
        required: true

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-caliper:
    name: Publish Caliper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    # anchor to the smallest npm version supporting trusted publishing
    - name: Update npm
      run: npm install -g npm@11.5.1
    - name: Publish Caliper
      run: .build/publish-caliper.sh
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
