name: Unit Tests

on:
  workflow_call:

env:
  NPM_VERSION: 8.15.0

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install higher version of NPM
      run: npm install -g npm@${{ env.NPM_VERSION }}
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ matrix.node-version }}-npm-cache-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.node-version }}-npm-cache-
    - name: Check correct usage of Caliper package names
      run: ./scripts/check-package-names.sh
    - name: Install project dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm ci
    - name: Check the version consistency of subpackages
      run: ./packages/caliper-publish/publish.js version check
    - name: Run unit tests
      run: npm test --workspaces
    - name: Upload coverage reports artifact
      if: matrix.node-version == '18.x'
      uses: actions/upload-artifact@v4.4.0
      with:
        name: coverage-reports
        path: packages/*/coverage/clover.xml
